projects:
  amplifytest:
    schemaPath: amplify/backend/api/amplifytest/build/schema.graphql
    includes:
      - graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
